In [1]:
import numpy as np

In [2]:
def swap_rows(matrix, row1, row2):
    print("S", row1, row2)
    matrix[[row1, row2]] = matrix[[row2, row1]]

def gaussian_elimination_inverse(matrix):
    n = len(matrix)
    augmented_matrix = np.hstack((matrix, np.identity(n)))

    for i in range(n):
        # Find the pivot row and swap rows if necessary
        max_index = np.argmax(np.abs(augmented_matrix[i:, i])) + i
        if max_index != i:
            swap_rows(augmented_matrix, i, max_index)

        # Check if the matrix is singular (non-invertible)
        if augmented_matrix[i, i] == 0:
            raise ValueError("The input matrix is singular and non-invertible.")

        # Normalize the pivot row
        augmented_matrix[i] /= augmented_matrix[i, i]

        # Eliminate the pivot entry in other rows
        for j in range(n):
            if j != i:
                factor = -augmented_matrix[j, i]
                augmented_matrix[j] += factor * augmented_matrix[i]

    inverse_matrix = augmented_matrix[:, n:]
    return inverse_matrix

In [3]:
# Example usage
A = np.array([[3, 2], [1, 1]])

In [4]:
A[0]

array([3, 2])

In [5]:
A_inv = gaussian_elimination_inverse(A)
print("A:\n", A)
print("Inverse of A:\n", A_inv)

A:
 [[3 2]
 [1 1]]
Inverse of A:
 [[ 1. -2.]
 [-1.  3.]]


In [6]:
from numpy.linalg import inv

inv(A)

array([[ 1., -2.],
       [-1.,  3.]])

In [13]:
' '.join(map(str, A[0]))

'3 2'

In [14]:
n = int(input())

arr = []
for r in range(n):
    inp = list(map(float, input().split()))
    arr.append(np.array(inp))

arr = np.array(arr)

2
3 2
[3.0, 2.0]
1 1
[1.0, 1.0]


In [15]:
arr

array([[3., 2.],
       [1., 1.]])